### ISSUE TITLE
Incorporating Element Mover's Distance / DensMAP chemical novelty embeddings

### ISSUE THREAD

**Issue by sgbaird** [mpds-io/tutorial#2]
Any interest in this? The thought came to mind while browsing [Vickers Hardness in MPDS](https://mpds.io/#plot/discovery/inquiry/props=vickers%20hardness%20number). For the most part, it seemed like to the left were binary compounds and to the right were ternaries, quaternaries, etc.

Here is [an example of the DensMAP embeddings](https://mat-discover.readthedocs.io/en/latest/figures.html#densmap-embeddings-colored-by-cluster) along with some other plots that also might make for interesting visualizations.

See also https://elmd.io/plots/ which is where the original idea came from, i.e.:
> Hargreaves, C. J.; Dyer, M. S.; Gaultois, M. W.; Kurlin, V. A.; Rosseinsky, M. J. The Earth Mover’s Distance as a Metric for the Space of Inorganic Compositions. Chem. Mater. 2020, 32 (24), 10610–10620. https://doi.org/10.1021/acs.chemmater.0c03381.

I don't have much experience with web development, but I can certainly help with the Python code if this is of interest. Happy to answer any questions, too.

Btw, really impressed with the slick interface of MPDS. Thank you for [suggesting it to me](https://matsci.org/t/literature-references-associated-with-chemical-formulas-or-compounds/39104/7?u=sgbaird).

**Comment by blokhin** [comment]
Hi @sgbaird many thanks for the nice encouraging suggestion! I'll write you an email in the next few days so we can discuss that tête-à-tête.

**Comment by sgbaird** [comment]
Sounds good!
